"use client"

import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Appbar from "@/components/custom/Appbar";
import { Footer } from "@/components/custom/Footer";
import { Providers } from "./providers";
import { usePathname } from "next/navigation";
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

 const metadata: Metadata = {
  title: "YFQR",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathname = usePathname()
  const minimalPaths = ['/']

  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {!minimalPaths.includes(pathname) && <Appbar />}
        <Providers>{children}</Providers>
        {!minimalPaths.includes(pathname) && <Footer />}
      </body>
    </html>
  );
}
